Add Css files
Usenko57/OnlineStore pull request #2
Opened 2020-04-09 15:44 UTC by Usenko57

Как вы и просили, ответвление от мастера сделано после добавления css файлов.

2020-04-10 12:14 UTC, gmltA commented
А па якому адрасу зараз глядзець саму старонку?

2020-04-10 12:21 UTC, Usenko57 commented
> А па якому адрасу зараз глядзець саму старонку?

вот тут тогда: https://usenko57.github.io/MySite/

2020-04-10 14:04 UTC, gmltA requested changes
1. У вас адсутнічае мабільная версія сайту ўвогуле.
2. Стылі надта простыя. Паспрабуйце паглядзець на якія-небудзь падобныя сайты і рэалізуйце больш складаны дызайн.
3. Не ўсе інтэрактыўныя элементы маюць стылі `hover`. Лепей, каб яны былі.
4. Паспрабуйце выкарыстоўваць нестандартныя шрыфты. Раю паспрабаваць Roboto, ці яшчэ што-небудзь адсюль: https://fonts.google.com/
5. У вашых стылях няма сэнсу выкарыстоўваць `float`. Яго трэба будзе замяніць.
6. Звярніце, калі ласка, увагу на артыкул, які я пакінуў у адным з каментаў. Ён дапаможа вам трошкі больш сумленна вызначаць сэлектары для стыляў.

Вы можаце дасылаць новыя каміты ў гэтую ж галіну: яны аўтаматычна дадаюцца ў pull request. Як выправіце ўсё, запрасіце review яшчэ раз.

2020-04-10 14:04 UTC, gmltA commented on Css/Basket.css
> +	float: right;
Выкарыстоўвайце, калі ласка, іншыя сродкі пазіцыяніравання, замест float (flex, grid).

2020-04-10 14:04 UTC, gmltA commented on Css/Basket.css
> +	margin-top: -15px;
Навошта тут адмоўны padding? Калі вам трэба, каб адлегласць паміж гэтым элементам і папярэднім была менш, трэба зрабіць менш водступ у папярэдняга элементу.

2020-04-10 14:04 UTC, gmltA commented on Css/Basket.css
> +	overflow: visible;
Навошта тут `overflow`?

2020-04-10 14:04 UTC, gmltA commented on Css/Basket.css
> +#phoneName {
**id** павінен быць унікальным на старонке. Не думаю, што ў вас у кошыку з некалькімі тэлефонамі будзе толькі адзін такі элемент. Выкарыстоўвайце для стылізацыі **class**, а не **id**.

2020-04-10 14:04 UTC, gmltA commented on Css/Home.css
> +#blackout:target {
Навошта патрэбен гэты стыль?

2020-04-10 14:04 UTC, gmltA commented on Css/Home.css
> +body > h1{
Замест тыкіх сэлектараў лепей выкарыстоўваць назвы класаў. Гэта агульная праблема ў вашых стылях. Прачытайце, калі ласка, вось гэты артыкул: https://ru.bem.info/methodology/quick-start/ і паспрабуйце перапрацаваць свае стылі ў адпаведнасці такой канвенцыі.

2020-04-10 14:04 UTC, gmltA commented on Css/Home.css
> +[type="email"], [type="password"] {
Такі сэлектар будзе працаваць на любых элементах з атрыбутам `type="email"`.
У тым ліку, напрыклад, на такіх: `<div type="email">`. У вашым выпадку толькі інпуты павінны быць стылізаваныя ў гэтым блоку.

2020-04-10 14:04 UTC, gmltA commented on Css/Home.css
> +	border-top-width: 0.1px;
Не трэба выкарыстоўваць велічыню ў пікселях з дробнай часткаю. На маніторах нельга намаляваць 1/10 пікселя і кожны браўзер можа спрабаваць зрабіць гэта па-рознаму (стандарту такой апрацоўцы няма), таму такіх выпадкаў трэба пазбягаць.

2020-04-10 14:04 UTC, gmltA commented on Css/Home.css
> +#from, #to{
Інпуты з максімальным і мінімальным коштам у вас маюць неверны атрыбут `type`.

2020-04-24 22:00 UTC, Usenko57 commented
> 1. У вас адсутнічае мабільная версія сайту ўвогуле.
> 2. Стылі надта простыя. Паспрабуйце паглядзець на якія-небудзь падобныя сайты і рэалізуйце больш складаны дызайн.
> 3. Не ўсе інтэрактыўныя элементы маюць стылі `hover`. Лепей, каб яны былі.
> 4. Паспрабуйце выкарыстоўваць нестандартныя шрыфты. Раю паспрабаваць Roboto, ці яшчэ што-небудзь адсюль: https://fonts.google.com/
> 5. У вашых стылях няма сэнсу выкарыстоўваць `float`. Яго трэба будзе замяніць.
> 6. Звярніце, калі ласка, увагу на артыкул, які я пакінуў у адным з каментаў. Ён дапаможа вам трошкі больш сумленна вызначаць сэлектары для стыляў.
> 
> Вы можаце дасылаць новыя каміты ў гэтую ж галіну: яны аўтаматычна дадаюцца ў pull request. Як выправіце ўсё, запрасіце review яшчэ раз.

> 1. У вас адсутнічае мабільная версія сайту ўвогуле.
> 2. Стылі надта простыя. Паспрабуйце паглядзець на якія-небудзь падобныя сайты і рэалізуйце больш складаны дызайн.
> 3. Не ўсе інтэрактыўныя элементы маюць стылі `hover`. Лепей, каб яны былі.
> 4. Паспрабуйце выкарыстоўваць нестандартныя шрыфты. Раю паспрабаваць Roboto, ці яшчэ што-небудзь адсюль: https://fonts.google.com/
> 5. У вашых стылях няма сэнсу выкарыстоўваць `float`. Яго трэба будзе замяніць.
> 6. Звярніце, калі ласка, увагу на артыкул, які я пакінуў у адным з каментаў. Ён дапаможа вам трошкі больш сумленна вызначаць сэлектары для стыляў.
> 
> Вы можаце дасылаць новыя каміты ў гэтую ж галіну: яны аўтаматычна дадаюцца ў pull request. Як выправіце ўсё, запрасіце review яшчэ раз.

 Добавлена мобильная версия сайта и произведена работа над ошибками. Хотел конечно сделать стиль получше, в плане добавить иконки на навигационную панель вместо надписей: корзина, войти. Но я не смог найти иконки нужного цвета, пытался вместить те, что находил, но они по цвету вообще не подошли.  Я думаю, что надо оставить так как есть.  Вот ссылка: https://usenko57.github.io/MySite/index.html

2020-04-27 15:05 UTC, gmltA requested changes
А дзе код новы? Дадайце яго сюды ж, калі ласка. Каб я бачыў адрозненні.

2020-04-27 16:09 UTC, Usenko57 commented
.

2020-04-27 16:33 UTC, Usenko57 commented
Я точно не знаю, но по ходу проблема в том, что я отравил новый код на
ветку с помощью команды push -f. То есть force, по той причине, что не
отправлялись изменения через просто push. Наверное существовали конфликты
между ветками. Честно сказать, я даже в истории коммитов на гитхабе не вижу
этот коммит. А вы наверное поэтому и не видите новых изменения. Можно ли
как то решить данную проблему, мб откатом команды push force на старый
коммит и заново запушить мой новый код?
пн, 27 апр. 2020 г. в 18:05, Alex Avetsiuk <notifications@github.com>:

> *@gmltA* requested changes on this pull request.
>
> А дзе код новы? Дадайце яго сюды ж, калі ласка. Каб я бачыў адрозненні.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Usenko57/OnlineStore/pull/2#pullrequestreview-401044499>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJN4HTHFD265NLVKJV36HTTROWNMFANCNFSM4ME2P73Q>
> .
>

2020-04-27 18:31 UTC, Usenko57 commented
.

2020-04-27 18:40 UTC, Usenko57 commented
.

2020-04-28 01:07 UTC, Usenko57 commented
Проблемка нарисовалась, благо разобрался тут, git force сделал до этого и все коммиты ушли, пришлось восстанавливать. Сейчас нормально?

2020-04-28 12:47 UTC, gmltA requested changes
Зрабіце, калі ласка, каб вашыя чекбоксы выглядалі вось так:

![image](https://user-images.githubusercontent.com/138737/80488277-c26fd580-8966-11ea-93f0-9ad49314d0b0.png)

2020-04-28 12:47 UTC, gmltA commented on Css/Home.css
> +#blackout:target {
Усё яшчэ не бачу адказу на мінулае пытанне пра гэты стыль.

2020-04-28 12:47 UTC, gmltA commented on Html/FilterMobileVersion.html
> +					<span class="flex-container__option-title">Слова в названии</span>
Трэба, каб гэта быў `label` для інпуту.

2020-04-28 12:47 UTC, gmltA commented on Html/FilterMobileVersion.html
> +							value="Samsung">Samsung<br>
Тут таксама лейбл патрэбен, `<br>` выдаліць.

2020-04-28 12:47 UTC, gmltA commented on Html/Baske.html
> +	<ul class="menu">
Тут павінен быць тэг навігацыі

2020-04-28 13:34 UTC, Usenko57 commented on Css/Home.css
> +#blackout:target {
Тут наверное просто не хватает пока что js. Я просто хотел чтобы модальное окно с авторизацией появлялось по переходу по ссылке. Display: none его скрывает до тех пор, пока мы его не открыли. Ну если открыли, то соответственно display: block становится.

2020-04-28 13:41 UTC, gmltA commented on Css/Home.css
> +#blackout:target {
У сэнсе «напэўна»? Гэта ваш код увогуле? Растлумачце правіла мне гэтае.

2020-04-28 16:48 UTC, Usenko57 commented on Css/Home.css
> +#blackout:target {
Код  полностью мой. Тут происходит следующее: по умолчанию у блока(id = blackout) стоит display:none, но если мы на навигационной панели сверху нажимаем на ссылку "войти", то срабатывает селектор #blackout:target (в котором уже display: block), и появляется модальное окно с авторизацией. Я сказал наверное, потому что пока подробно не разбирался в javascript, и думаю, что может быть там как то тоже можно описать этот момент.

2020-04-29 15:38 UTC, gmltA commented on Css/Home.css
> +#blackout:target {
Прынята.

2020-05-03 09:05 UTC, Usenko57 commented
https://usenko57.github.io/MySite/ ещё раз скину ссылку вам, чтобы вверху не искать, вроде исправил всё

2020-05-04 16:41 UTC, gmltA approved these changes
Добра. Працуйце далей.

2020-05-04 19:31 UTC, merged