Work with js
Usenko57/OnlineStore pull request #3
Opened 2020-05-12 20:11 UTC by Usenko57

https://usenko57.github.io/MySite/ 
Высылаю вам бета-версию js. Хотелось бы услышать замечания о недостатках на данном этапе. Создана инициализация телефонов в списке. Они могут добавляться в корзину. Но сразу скажу о минусах: 
1)Не удалось до сих пор разобраться как размер фрэйма делать таким по высоте, как он есть. Я использую тег object при вставке фрэйма в блок, хоть вы и не советовали этого делать, к сожалению лучше совета я пока нигде не нашёл в интернете. Самая большая беда, что я использую там пока что height=200hv чтобы увидеть всё содержимое home.html, но это height, потом распространяется на несколько компонентов.
2)Пока что не сделал добавление в корзину со стороны mobileDescription(так называемая detail-page)
3) Хотелось бы не видеть шапку навигационной панели в мобильной версии при фильтрации телефонов, но пока тоже не возникает мыслей как это сделать(

Если со стороны js ещё что то не затронул, то пожалуйста скажите. 
Также хотел ещё задать вам вопрос не по теме: вы говорили, что тем кто сдал чат, будет проще немного сдать проект. Это типо то, что будет просто меньше требований по проекту?

Спасибо за терпение, после прочитанного сообщения)

2020-05-14 12:58 UTC, gmltA commented
> 1)Не удалось до сих пор разобраться как размер фрэйма делать таким по высоте, как он есть. Я использую тег object при вставке фрэйма в блок, хоть вы и не советовали этого делать, к сожалению лучше совета я пока нигде не нашёл в интернете. Самая большая беда, что я использую там пока что height=200hv чтобы увидеть всё содержимое home.html, но это height, потом распространяется на несколько компонентов.

Гэта ўвогуле дрэнны падыход. Замест гэтага вы павінны працаваць з разметкаю ў межах адной старонкі пры дапамозе скрыптоў.



> 3) Хотелось бы не видеть шапку навигационной панели в мобильной версии при фильтрации телефонов, но пока тоже не возникает мыслей как это сделать(

Не зразумеў, аб чым вы.

2020-05-14 13:06 UTC, gmltA requested changes

2020-05-14 13:06 UTC, gmltA commented on Css/MobileDescription.css
> +		top: 800px;
Не, так рабіць не трэба. Выкарыстоўвайце, калі ласка, flex ці grid дзеля гэтага.

2020-05-14 13:06 UTC, gmltA commented on Js/Basket.js
> +var table = document.getElementById('phoneTable');
Тут і далей выкарыстоўвайце `const` ці `let`, калі ласка.

2020-05-14 13:06 UTC, gmltA commented on Js/Home.js
> +var phone3 = new MobilePhone("phone3","Apple iPhone Xr 64Gb Red", "../Images/Phone3.jpg","Apple", "iOS",
Дадайце іх усе ў адзін масіў.

2020-05-14 13:06 UTC, gmltA commented on Js/Home.js
> +setPhoneToList(phone);
А тут па гэтаму масіву прайдзіцеся і для кожнага элементу ў ім выклікайце гэты метад.

2020-05-14 13:06 UTC, gmltA commented on Js/Home.js
> +	let basket_buttons = event.target.parentElement.parentElement.parentElement.getElementsByClassName('phone-container__toBasket');
`parentElement.parentElement.parentElement` так рабіць не трэба. Выкарыстоўвайце `document.querySelector`

2020-05-15 11:46 UTC, Usenko57 commented
> > 1)Не удалось до сих пор разобраться как размер фрэйма делать таким по высоте, как он есть. Я использую тег object при вставке фрэйма в блок, хоть вы и не советовали этого делать, к сожалению лучше совета я пока нигде не нашёл в интернете. Самая большая беда, что я использую там пока что height=200hv чтобы увидеть всё содержимое home.html, но это height, потом распространяется на несколько компонентов.
> 
> Гэта ўвогуле дрэнны падыход. Замест гэтага вы павінны працаваць з разметкаю ў межах адной старонкі пры дапамозе скрыптоў.

Я использую теперь ajax для подгрузки контента, но почему то не срабатывает document.getElementById() в загружаемом html файле, может вы знаете причину почему так происходит и как сделать так, чтобы я всё таки получал по id элемент?

2020-05-15 13:59 UTC, gmltA commented
> > > 1)Не удалось до сих пор разобраться как размер фрэйма делать таким по высоте, как он есть. Я использую тег object при вставке фрэйма в блок, хоть вы и не советовали этого делать, к сожалению лучше совета я пока нигде не нашёл в интернете. Самая большая беда, что я использую там пока что height=200hv чтобы увидеть всё содержимое home.html, но это height, потом распространяется на несколько компонентов.
> > 
> > 
> > Гэта ўвогуле дрэнны падыход. Замест гэтага вы павінны працаваць з разметкаю ў межах адной старонкі пры дапамозе скрыптоў.
> 
> Я использую теперь ajax для подгрузки контента, но почему то не срабатывает document.getElementById() в загружаемом html файле, может вы знаете причину почему так происходит и как сделать так, чтобы я всё таки получал по id элемент?

Магчыма, вы выклікаеце функцыю вельмі рана. Паспрабуйце паглядзець больш дэтальна ў тое, што ў вас там адбываецца. Калі не атрымаецца, скідвайце код сюды — паглядзім.

2020-05-15 14:16 UTC, Usenko57 commented
> > > > 1)Не удалось до сих пор разобраться как размер фрэйма делать таким по высоте, как он есть. Я использую тег object при вставке фрэйма в блок, хоть вы и не советовали этого делать, к сожалению лучше совета я пока нигде не нашёл в интернете. Самая большая беда, что я использую там пока что height=200hv чтобы увидеть всё содержимое home.html, но это height, потом распространяется на несколько компонентов.
> > > 
> > > 
> > > Гэта ўвогуле дрэнны падыход. Замест гэтага вы павінны працаваць з разметкаю ў межах адной старонкі пры дапамозе скрыптоў.
> > 
> > 
> > Я использую теперь ajax для подгрузки контента, но почему то не срабатывает document.getElementById() в загружаемом html файле, может вы знаете причину почему так происходит и как сделать так, чтобы я всё таки получал по id элемент?
> 
> Магчыма, вы выклікаеце функцыю вельмі рана. Паспрабуйце паглядзець больш дэтальна ў тое, што ў вас там адбываецца. Калі не атрымаецца, скідвайце код сюды — паглядзім.

1)файл для роутинга
function getPage(page){
	var xHttpReq = new XMLHttpRequest();
	xHttpReq.onreadystatechange = function() {
		if(this.readyState == 4 && this.status == 200){			
			document.getElementById('content').innerHTML = this.responseText;
		}
	}

	xHttpReq.open('GET', page, true);	
	xHttpReq.send();
}
getPage('Html/Home.html');

2)   ссылка для добавления контента в блок на главной странице (index.html)
     <a id=goHome class="menu__ref"  onclick="getPage('Html/Home.html')" href="#">Интернет- 
        магазин</a>
       <div id=content>
       </div> 
3) В добавляемом Home.html присутствует <ul id=phone_list class="phone-container__model-list"> и скрипт подключаемый к главной странице(index.html), не видит элемент по следующему запросу: document.getElementById('phone_list');

2020-05-15 14:28 UTC, Usenko57 commented
> > > > 1)Не удалось до сих пор разобраться как размер фрэйма делать таким по высоте, как он есть. Я использую тег object при вставке фрэйма в блок, хоть вы и не советовали этого делать, к сожалению лучше совета я пока нигде не нашёл в интернете. Самая большая беда, что я использую там пока что height=200hv чтобы увидеть всё содержимое home.html, но это height, потом распространяется на несколько компонентов.
> > > 
> > > 
> > > Гэта ўвогуле дрэнны падыход. Замест гэтага вы павінны працаваць з разметкаю ў межах адной старонкі пры дапамозе скрыптоў.
> > 
> > 
> > Я использую теперь ajax для подгрузки контента, но почему то не срабатывает document.getElementById() в загружаемом html файле, может вы знаете причину почему так происходит и как сделать так, чтобы я всё таки получал по id элемент?
> 
> Магчыма, вы выклікаеце функцыю вельмі рана. Паспрабуйце паглядзець больш дэтальна ў тое, што ў вас там адбываецца. Калі не атрымаецца, скідвайце код сюды — паглядзім.

1)Я использую следующий скрипт для роутинга:
```
function getPage(page){
	var xHttpReq = new XMLHttpRequest();
	xHttpReq.onreadystatechange = function() {
		if(this.readyState == 4 && this.status == 200){			
			document.getElementById('content').innerHTML = this.responseText;
		}
	}

	xHttpReq.open('GET', page, true);	
	xHttpReq.send();
}

getPage('Html/Home.html');
```
2) главная страница(index.html) содержит следующие компоненты:
```
<a id=goHome class="menu__ref"  onclick="getPage('Html/Home.html')" href="#">Интернет-магазин</a>
<div id=content>
	</div>	
```
3) загружаемая страница(Home.html) содержит следующий компонент: 
```
<ul id=phone_list class="phone-container__model-list">
			</ul>
```
4) Скрипт, подключаемый к главной странице(index.html) не видит элемент по следующему запросу: 
```
document.getElementById('phone_list');	
```

2020-05-18 13:56 UTC, gmltA commented
А пакажыце, у які момант выконваецца гэты скрыпт, які не працуе.

2020-05-18 15:57 UTC, Usenko57 commented
> А пакажыце, у які момант выконваецца гэты скрыпт, які не працуе.

<img width="960" alt="Безымянный" src="https://user-images.githubusercontent.com/39568332/82233650-ff613380-9938-11ea-921c-4b50ef0af91e.png"> 
Вот порядок вызова скриптов, Ajax.js заполняет ```<div id=content></div>``` новой вызываемой страницей. Выделенный скрипт Home.js выполняется, НО он не видит по id элементов из загруженной странице в блок с id=content....

2020-05-19 15:48 UTC, gmltA commented
Лепей за ўсё ўвесь код, які працуе з DOM выконваць пасля эвенту `DOMContentLoaded`

2020-05-23 14:20 UTC, Usenko57 commented
Есть 1 минус, который я планирую решить на уровне бэкэнда: добавление в корзину ИЗ страницы описания с телефоном. Из главной страницы телефоны в порядке вещей добавляются в корзину.

2020-05-24 07:45 UTC, gmltA requested changes

2020-05-24 07:45 UTC, gmltA commented on Js/Basket.js
> +	var chooseAllPhones;
А што вы такім чынам хочаце зрабіць?

2020-05-24 07:45 UTC, gmltA commented on Js/Home.js
> +	var i;
І тут.

Здаецца, вы не зусім разумееце, як працаваць са зменнымі.
Па-першае, не выкарыстоўваць `var`.
Па-другое скоўп зменнай - блок, у якім яна была створана. У дадзеным выпадку `var` "усплывае" вышэй, але такія паводзіны не трэба выкарыстоўваць.
І давайце, калі ласка, асэнсаваныя назвы зменным.

2020-05-24 07:45 UTC, gmltA commented on Js/MobileDescription.js
> +			phone.inBasket = true;
Здаецца мне, вам трэба не ўнутры мадэлі тэлефону ствараць property `inBasket`, а зрабіць об'ект basket, у які дадаваць тэлефон.

2020-05-24 22:12 UTC, Usenko57 commented
https://onlinestore-99789.web.app/ 
Посмотрите пожалуйста этот коммит.

2020-05-25 19:49 UTC, gmltA approved these changes
Зараз добра. Што засталося?

2020-05-25 20:19 UTC, Usenko57 commented
> Зараз добра. Што засталося?

Смотрите, я сейчас делаю аунтефикацию через сервис firebase. В бэкэнде я сделаю следующее: post запрос на покупку телефонов, лежащих в корзине и get запрос на фильтрацию телефонов. Планирую сделать 2 таблицы, 1 с юзерами, вторую с телефонами. И у юзера будет храниться в таблице поле с массивом внешних ключей(купленных телефонов) и количество денег, которое он оставил в магазине. Это весь функционал, который я планирую сделать. У  меня экзамен в пятницу, можно ли я вот то что написал вам сейчас, сделаю одним следующим реквестом на другой ветке?

2020-05-25 20:33 UTC, gmltA commented
> можно ли я вот то что написал вам сейчас, сделаю одним следующим реквестом на другой ветке?

Так, канешне. На тое і быў разлік. Гэта мержыце з master, стварайце адразу ж новую галіну і працуйце ўжо ў ёй.

2020-05-25 20:35 UTC, merged